namespace TMFChar.Gen;

// <autogenerated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
public partial class ResourceCharacteristics
{
    protected ResourceCharacteristics() { }

    public string DecisionDate => "decision date";
    public string LayoutConfiguration => "LayoutConfiguration";
    public string Deliverables => "Deliverables";
    public string PlanDateForColdBuild => "Plan date for cold build";
    public string PartnerReferenceNumber => "Partner Reference Number";
    public string DeliverablesFiles => "Deliverables Files";
    public string PONumber => "PO Number";
    public string Checklist => "Checklist";
    public string ChangeTicketID => "Change Ticket ID";
    public string VerificationDate => "Verification Date";
    public string CallOfRequisitionInOFC => "Call of Requisition in OFC";
    public string EndDate => "End Date";
    public string ActualCompletionDate => "Actual completion date";
    public string StartDate => "Start Date";
    public string VerificationDocuments => "Verification documents";
    public string ColdBuildFiles => "Cold build files";
    public string TechnicianForVerification => "Technician for Verification";
    public string FromTo => "FromTo";
    public string WarmBuildFiles => "Warm build files";
    public string TechnicianForWarmBuild => "Technician for warm build";
    public string Date => "Date";
    public string ChangeTicketStatus => "Change Ticket Status";
    public string TestStatus => "Test Status";
    public string Status => "Status";
    public string Tasks => "Tasks";
    public string TestStartDate => "Test Start date";
    public string TestDate => "Test date";
    public string Test => "Test";
    public string TechnicianForTesting => "Technician for testing";
    public string Documents => "Documents";
    public string TestChangeTicketID => "Test Change Ticket ID";
    public string TestEndDate => "Test End date";
    public string HandoverFiles => "Handover files";
    public string RevisionFiles => "Revision Files";
    public string OperationsTeam => "Operations team";
    public string DeliveryCheck => "Delivery check";

    public static string Get(Func<ResourceCharacteristics, string> picker)
    {
        return picker(new ResourceCharacteristics());
    }
}
