namespace TMFChar.Gen;

// <autogenerated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
public partial class ServiceCharacteristics
{
    protected ServiceCharacteristics() { }

    public string Quantity => "quantity";
    public string ServiceOrderId => "serviceOrderId";
    public string ProjectNumber => "projectNumber";
    public string CustomerOrderId => "customerOrderId";
    public string ServiceType => "serviceType";
    public string ProjectName => "projectName";
    public string ServiceName => "serviceName";
    public string Urgency => "urgency";
    public string ProjectDescription => "projectDescription";
    public string TotalBudget => "totalBudget";
    public string TechnicalDeliveryDate => "technicalDeliveryDate";
    public string LocationCount => "locationCount";
    public string RelatedProjects => "relatedProjects";
    public string Locations => "locations";
    public string DevicesPerSite => "devicesPerSite";
    public string LayoutConfiguration => "layoutConfiguration";
    public string OtherDocs => "otherDocs";
    public string MandatoryDocs => "mandatoryDocs";
    public string UrgencyDescription => "urgencyDescription";

    public static string Get(Func<ServiceCharacteristics, string> picker)
    {
        return picker(new ServiceCharacteristics());
    }
}
